version: "3"

services:
  uga-bot-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=uga_bot
      - MYSQL_USER=uga_bot
      - MYSQL_PASSWORD=uga_bot
    ports:
      - 3308:3306

  uga-bot-app:
    build: .
    restart: on-failure
    depends_on:
      - uga-bot-mysql
    ports:
    - 8080:8080
    environment:
    - DISCORD_TOKEN=${DISCORD_TOKEN} # This gets pulled out of the .env file